name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet workload update && dotnet tool install -g KuiperZone.PupNet
      - name: Install PupNet
        run: pip3 install iscc-cli
      - name: Build
        run: pupnet -r win-x64 -k setup
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: Deploy/OUT

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: Deploy/OUT
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Passe die Version entsprechend an
          release_name: Release v1.0.0
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Deploy/OUT
          asset_name: Avalonia.CoffeeShop.exe
          asset_content_type: application/exe